
language: python

python:

    - "2.7"

install:

    - "pip install -r requirements.txt --use-mirrors"

script:

    - "coverage run --source=pydocbuild setup.py test"

after_success:

    pydocbuild
